
package info.catarc.tsoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FuelDataSysSTDTest", targetNamespace = "http://tsoap.catarc.info/", wsdlLocation = "http://tsoap.catarc.info/FuelDataSysSTDTest.asmx?wsdl")
public class FuelDataSysSTDTest
    extends Service
{

    private final static URL FUELDATASYSSTDTEST_WSDL_LOCATION;
    private final static WebServiceException FUELDATASYSSTDTEST_EXCEPTION;
    private final static QName FUELDATASYSSTDTEST_QNAME = new QName("http://tsoap.catarc.info/", "FuelDataSysSTDTest");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://tsoap.catarc.info/FuelDataSysSTDTest.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FUELDATASYSSTDTEST_WSDL_LOCATION = url;
        FUELDATASYSSTDTEST_EXCEPTION = e;
    }

    public FuelDataSysSTDTest() {
        super(__getWsdlLocation(), FUELDATASYSSTDTEST_QNAME);
    }

    public FuelDataSysSTDTest(WebServiceFeature... features) {
        super(__getWsdlLocation(), FUELDATASYSSTDTEST_QNAME, features);
    }

    public FuelDataSysSTDTest(URL wsdlLocation) {
        super(wsdlLocation, FUELDATASYSSTDTEST_QNAME);
    }

    public FuelDataSysSTDTest(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FUELDATASYSSTDTEST_QNAME, features);
    }

    public FuelDataSysSTDTest(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FuelDataSysSTDTest(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FuelDataSysSTDTestSoap
     */
    @WebEndpoint(name = "FuelDataSysSTDTestSoap")
    public FuelDataSysSTDTestSoap getFuelDataSysSTDTestSoap() {
        return super.getPort(new QName("http://tsoap.catarc.info/", "FuelDataSysSTDTestSoap"), FuelDataSysSTDTestSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FuelDataSysSTDTestSoap
     */
    @WebEndpoint(name = "FuelDataSysSTDTestSoap")
    public FuelDataSysSTDTestSoap getFuelDataSysSTDTestSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tsoap.catarc.info/", "FuelDataSysSTDTestSoap"), FuelDataSysSTDTestSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FUELDATASYSSTDTEST_EXCEPTION!= null) {
            throw FUELDATASYSSTDTEST_EXCEPTION;
        }
        return FUELDATASYSSTDTEST_WSDL_LOCATION;
    }

}
