
package com.mes.webclient.vcpus.epi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSXxgkVinSoap", targetNamespace = "http://web1.vecc-mep.org.cn/WSXxgkVin")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSXxgkVinSoap {


    /**
     * <h3>登录中心服务接口，成功返回临时认证码32位KEY码，超时则需重新登录</h3><p>输入参数：manufid = 企业编号(机构代码)，不能为空；password =  报送密码；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param password
     * @param manufid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSXxgkVin/login")
    @WebResult(name = "loginResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
    @RequestWrapper(localName = "login", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.LoginResponse")
    public String login(
        @WebParam(name = "manufid", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String manufid,
        @WebParam(name = "password", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String password);

    /**
     * <h3>查询已报送VIN数</h3><p>输入参数： key = 临时认证码，不能为空；xshzh =  型式核准号；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param xxgkh
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSXxgkVin/getVinCountByXshzh")
    @WebResult(name = "getVinCountByXxgkhResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
    @RequestWrapper(localName = "getVinCountByXxgkh", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.GetVinCountByXxgkh")
    @ResponseWrapper(localName = "getVinCountByXxgkhResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.GetVinCountByXxgkhResponse")
    public String getVinCountByXxgkh(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String key,
        @WebParam(name = "xxgkh", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String xxgkh);

    /**
     * <h3>查询已报送VIN总数通过报送日期</h3><p>输入参数： key = 临时认证码，不能为空；dtFrom =  报送起始时间；dtTo =  报送截至时间；时间格式 YYYY-MM-DD HH24:MI:SS；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param dtTo
     * @param dtFrom
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSXxgkVin/getVinCountByDate")
    @WebResult(name = "getVinCountByDateResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
    @RequestWrapper(localName = "getVinCountByDate", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.GetVinCountByDate")
    @ResponseWrapper(localName = "getVinCountByDateResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.GetVinCountByDateResponse")
    public String getVinCountByDate(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String key,
        @WebParam(name = "dtFrom", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String dtFrom,
        @WebParam(name = "dtTo", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String dtTo);

    /**
     * <h3>查询已报送VIN所对应的环保信息码</h3><p>输入参数： key = 临时认证码，不能为空；vin =  vin号；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param vin
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSXxgkVin/getHbcodeByVin")
    @WebResult(name = "getHbcodeByVinResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
    @RequestWrapper(localName = "getHbcodeByVin", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.GetHbcodeByVin")
    @ResponseWrapper(localName = "getHbcodeByVinResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.GetHbcodeByVinResponse")
    public String getHbcodeByVin(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String key,
        @WebParam(name = "vin", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String vin);

    /**
     * <h3>删除已上报VIN信息</h3><p>输入参数： key = 临时认证码，不能为空；vin =  vin号；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param vin
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSXxgkVin/delData")
    @WebResult(name = "delDataResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
    @RequestWrapper(localName = "delData", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.DelData")
    @ResponseWrapper(localName = "delDataResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.DelDataResponse")
    public String delData(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String key,
        @WebParam(name = "vin", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String vin);

    /**
     * <h3>退出本次连接</h3><p>输入参数；Key = 临时认证码，不能为空；返回数据：一个标准的XML字符串<br /><br><br><br><br><p>
     * 
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSXxgkVin/logout")
    @WebResult(name = "logoutResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
    @RequestWrapper(localName = "logout", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.LogoutResponse")
    public String logout(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String key);

    /**
     * <h3>上报Vin数据；注意，报送成功后1小时以后才会算正式报送完成</h3><p>输入参数： key = 临时认证码，不能为空；strVinData:  信息主体<br><br><br><br><p>
     * 
     * @param strVinData
     * @param key
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://web1.vecc-sepa.org.cn/WSXxgkVin/sendVinData")
    @WebResult(name = "sendVinDataResult", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
    @RequestWrapper(localName = "sendVinData", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.SendVinData")
    @ResponseWrapper(localName = "sendVinDataResponse", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin", className = "com.mes.webclient.vcpus.epi.SendVinDataResponse")
    public String sendVinData(
        @WebParam(name = "key", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String key,
        @WebParam(name = "strVinData", targetNamespace = "http://web1.vecc-sepa.org.cn/WSXxgkVin")
        String strVinData);

}
